### ISSUE TITLE
PropType Error

### ISSUE THREAD

**Issue by jonfairbanks** [crisboarna/react-skillbars#125]
Using **react-skillbars**, I get a PropType error from `colors`:

` t: type specification of prop 'colors' is invalid; the type checker function must return 'null' or an 'Error' but returned a function. You may have forgotten to pass an argument to the type checker creator (arrayOf, instanceOf, objectOf, oneOf, oneOfType, and shape all require an argument).`

Swapping `colors` from `.shape` to `.object` resolves this.

**Comment by jonfairbanks** [comment]
I have opened PR #123 to resolve this issue. @crisboarna: Can you review and merge, please?

**Comment by crisboarna** [comment]
Hey @jonfairbanks , thank you very much for the PR and I am sorry this may be a bit late, but I have updated the project to Typescript.

While I know the PropType is runtime and TS types are compile time and that there are plugins that can be added to automatically generate PropTypes from TS types think compile time gives more advantages overall. 

If you want you can raise another PR that adds in PropTypes from TS instead of alongside to avoid repetition. Promise it won't take as long to review and merge the next one ^^'
